flag_management:
  default_rules:
    statuses:
      - type: project
        target: 90%
        threshold: 1%
      - type: patch
        target: 90%
  individual_flags:
    - name: xcm-sdk-core
      paths:
        - packages/sdk-core
      carryforward: true
    - name: xcm-sdk
      paths:
        - packages/sdk
      carryforward: true
    - name: xcm-sdk-pjs
      paths:
        - packages/sdk-pjs
      carryforward: true
    - name: sdk-common
      paths:
        - packages/sdk-common
      carryforward: true
    - name: assets
      paths:
        - packages/assets
      carryforward: true
    - name: pallets
      paths:
        - packages/pallets
      carryforward: true
    - name: xcm-analyser
      paths:
        - packages/xcm-analyser
      carryforward: true
    - name: xcm-router
      paths:
        - packages/xcm-router
      carryforward: true
    - name: xcm-api
      paths:
        - apps/xcm-api
      carryforward: true
    - name: visualizator-be
      paths:
        - apps/visualizator-be
      carryforward: true

coverage:
  precision: 2
  round: down
  range: "90...100"
  status:
    project:
      default:
        target: 90%
    patch:
      default:
        target: 90%

comment:
  show_carryforward_flags: true
