import { TSubstrateChain } from '@paraspell/sdk-common'

export const chainToQuery: Record<TSubstrateChain, string[]> = {
  // Chain state query: <module>.<method> for assets metadata
  Polkadot: [],
  Kusama: [],
  Westend: [],
  Paseo: [],
  Acala: ['assetRegistry.assetMetadatas'],
  Ajuna: ['assets.metadata'],
  Astar: ['assets.metadata'],
  BifrostPolkadot: ['assetRegistry.currencyMetadatas'],
  Centrifuge: ['ormlAssetRegistry.metadata'],
  ComposableFinance: ['assetsRegistry.assetSymbol'],
  Darwinia: ['assets.metadata'],
  EnergyWebX: ['assets.metadata'],
  Hydration: ['assetRegistry.assets'],
  IntegriteeKusama: ['assets.metadata'],
  IntegriteePolkadot: ['assets.metadata'],
  Interlay: ['assetRegistry.metadata'],
  Heima: ['assets.metadata'],
  Jamton: ['assetRegistry.metadata'],
  Moonbeam: ['evmForeignAssets.assetsById'],
  AssetHubPolkadot: ['assets.metadata'],
  Altair: ['ormlAssetRegistry.metadata'],
  Amplitude: ['assetRegistry.metadata'],
  Basilisk: ['assetRegistry.assetMetadataMap'],
  BifrostKusama: ['assetRegistry.currencyMetadatas'],
  Crab: ['assets.metadata'],
  CrustShadow: ['assets.metadata'],
  Encointer: [], // No assets metadata query
  Karura: ['assetRegistry.assetMetadatas'],
  Kintsugi: ['assetRegistry.metadata'],
  Moonriver: ['evmForeignAssets.assetsById'],
  Laos: [], // No assets metadata query
  Quartz: ['foreignAssets.collectionToForeignAsset'],
  RobonomicsKusama: ['assets.metadata'],
  RobonomicsPolkadot: ['assets.metadata'],
  PeopleKusama: [], // Does not support ParaToPara transfers
  PeoplePolkadot: [], // Does not support ParaToPara transfers
  Shiden: ['assets.metadata'],
  AssetHubKusama: ['assets.metadata'],
  Unique: ['foreignAssets.collectionToForeignAsset'],
  Crust: ['assets.metadata'],
  Manta: ['assets.metadata'],
  Nodle: [],
  NeuroWeb: ['assets.metadata'],
  Pendulum: ['assetRegistry.metadata'],
  Zeitgeist: ['assetRegistry.metadata'],
  Collectives: [],
  Phala: ['assets.metadata'],
  CoretimeKusama: [],
  CoretimePolkadot: [],
  Subsocial: [], // No assets metadata query
  KiltSpiritnet: ['fungibles.metadata'],
  Curio: ['assetRegistry.metadata'],
  BridgeHubPolkadot: [],
  BridgeHubKusama: [],
  Mythos: [], // No assets metadata query
  Peaq: ['assets.metadata'],
  Polimec: ['foreignAssets.metadata'],
  // Westend chains
  AssetHubWestend: ['assets.metadata'],
  BridgeHubWestend: [],
  CollectivesWestend: [],
  CoretimeWestend: [],
  PeopleWestend: [],
  Penpal: ['foreignAssets.metadata'],
  // Paseo chains
  AssetHubPaseo: ['assets.metadata'],
  BridgeHubPaseo: [],
  CoretimePaseo: [],
  EnergyWebXPaseo: ['assets.metadata'],
  PAssetHub: ['assets.metadata'],
  PeoplePaseo: [],
  AjunaPaseo: ['assets.metadata'],
  BifrostPaseo: ['assetRegistry.currencyMetadatas'],
  HeimaPaseo: ['assets.metadata'],
  IntegriteePaseo: ['assets.metadata'],
  HydrationPaseo: ['assetRegistry.assets'],
  KiltPaseo: ['fungibles.metadata'],
  LaosPaseo: [], // No assets metadata query
  NeuroWebPaseo: ['assets.metadata'],
  NodlePaseo: [],
  ZeitgeistPaseo: ['assetRegistry.metadata']
}
