import type { TChain } from '@paraspell/sdk-common'

import type { TChainAssetsInfo } from '../src'
import { fetchEthereumAssets } from './fetchers/ethereum'

export const chainToQuery: Record<
  TChain,
  string | (() => Promise<TChainAssetsInfo>)
> = {
  // Chain state query: <Pallet>.<Storage> for assets metadata
  Kusama: '',
  Paseo: '',
  Polkadot: '',
  Westend: '',
  Acala: 'AssetRegistry.AssetMetadatas',
  Ajuna: 'Assets.Metadata',
  AjunaPaseo: 'Assets.Metadata',
  Astar: 'Assets.Metadata',
  AssetHubKusama: 'Assets.Metadata',
  AssetHubPaseo: 'Assets.Metadata',
  AssetHubPolkadot: 'Assets.Metadata',
  AssetHubWestend: 'Assets.Metadata',
  Basilisk: 'AssetRegistry.AssetMetadataMap',
  BifrostKusama: 'AssetRegistry.CurrencyMetadatas',
  BifrostPaseo: 'AssetRegistry.CurrencyMetadatas',
  BifrostPolkadot: 'AssetRegistry.CurrencyMetadatas',
  BridgeHubKusama: '',
  BridgeHubPaseo: '',
  BridgeHubPolkadot: '',
  BridgeHubWestend: '',
  Centrifuge: 'OrmlAssetRegistry.Metadata',
  Collectives: '',
  CollectivesWestend: '',
  CoretimeKusama: '',
  CoretimePaseo: '',
  CoretimePolkadot: '',
  CoretimeWestend: '',
  Crab: 'Assets.Metadata',
  Crust: 'Assets.Metadata',
  CrustShadow: 'Assets.Metadata',
  Darwinia: 'Assets.Metadata',
  Encointer: '',
  EnergyWebX: 'Assets.Metadata',
  EnergyWebXPaseo: 'Assets.Metadata',
  Heima: 'Assets.Metadata',
  HeimaPaseo: 'Assets.Metadata',
  Hydration: 'AssetRegistry.Assets',
  HydrationPaseo: 'AssetRegistry.Assets',
  Interlay: 'AssetRegistry.Metadata',
  Jamton: 'AssetRegistry.Metadata',
  Karura: 'AssetRegistry.AssetMetadatas',
  Kintsugi: 'AssetRegistry.Metadata',
  Moonbeam: 'EvmForeignAssets.AssetsById',
  Moonriver: 'EvmForeignAssets.AssetsById',
  Mythos: '',
  NeuroWeb: 'ForeignAssets.Metadata',
  NeuroWebPaseo: 'ForeignAssets.Metadata',
  Peaq: 'Assets.Metadata',
  Pendulum: 'AssetRegistry.Metadata',
  Penpal: 'ForeignAssets.Metadata',
  PeopleKusama: '',
  PeoplePaseo: '',
  PeoplePolkadot: '',
  PeopleWestend: '',
  Quartz: 'ForeignAssets.CollectionToForeignAsset',
  RobonomicsPolkadot: '',
  Shiden: 'Assets.Metadata',
  Unique: 'ForeignAssets.CollectionToForeignAsset',
  Xode: 'Assets.Metadata',
  Zeitgeist: 'AssetRegistry.Metadata',
  ZeitgeistPaseo: 'AssetRegistry.Metadata',

  // External chains
  Ethereum: () => fetchEthereumAssets(['polkadot_mainnet']),
  EthereumTestnet: () => fetchEthereumAssets(['paseo_sepolia', 'westend_sepolia'])
}
