import Acala from '../nodes/supported/Acala'
import Ajuna from '../nodes/supported/Ajuna'
import AjunaPaseo from '../nodes/supported/AjunaPaseo'
import Altair from '../nodes/supported/Altair'
import Amplitude from '../nodes/supported/Amplitude'
import AssetHubKusama from '../nodes/supported/AssetHubKusama'
import AssetHubPaseo from '../nodes/supported/AssetHubPaseo'
import AssetHubPolkadot from '../nodes/supported/AssetHubPolkadot'
import AssetHubWestend from '../nodes/supported/AssetHubWestend'
import Astar from '../nodes/supported/Astar'
import Basilisk from '../nodes/supported/Basilisk'
import BifrostKusama from '../nodes/supported/BifrostKusama'
import BifrostPaseo from '../nodes/supported/BifrostPaseo'
import BifrostPolkadot from '../nodes/supported/BifrostPolkadot'
import BridgeHubKusama from '../nodes/supported/BridgeHubKusama'
import BridgeHubPaseo from '../nodes/supported/BridgeHubPaseo'
import BridgeHubPolkadot from '../nodes/supported/BridgeHubPolkadot'
import BridgeHubWestend from '../nodes/supported/BridgeHubWestend'
import Centrifuge from '../nodes/supported/Centrifuge'
import Collectives from '../nodes/supported/Collectives'
import CollectivesWestend from '../nodes/supported/CollectivesWestend'
import ComposableFinance from '../nodes/supported/ComposableFinance'
import CoretimeKusama from '../nodes/supported/CoretimeKusama'
import CoretimePaseo from '../nodes/supported/CoretimePaseo'
import CoretimePolkadot from '../nodes/supported/CoretimePolkadot'
import CoretimeWestend from '../nodes/supported/CoretimeWestend'
import Crab from '../nodes/supported/Crab'
import Crust from '../nodes/supported/Crust'
import CrustShadow from '../nodes/supported/CrustShadow'
import Curio from '../nodes/supported/Curio'
import Darwinia from '../nodes/supported/Darwinia'
import Encointer from '../nodes/supported/Encointer'
import Heima from '../nodes/supported/Heima'
import HeimaPaseo from '../nodes/supported/HeimaPaseo'
import Hydration from '../nodes/supported/Hydration'
import HydrationPaseo from '../nodes/supported/HydrationPaseo'
import Interlay from '../nodes/supported/Interlay'
import Jamton from '../nodes/supported/Jamton'
import Karura from '../nodes/supported/Karura'
import KiltPaseo from '../nodes/supported/KiltPaseo'
import KiltSpiritnet from '../nodes/supported/KiltSpiritnet'
import Kintsugi from '../nodes/supported/Kintsugi'
import Laos from '../nodes/supported/Laos'
import LaosPaseo from '../nodes/supported/LaosPaseo'
import Manta from '../nodes/supported/Manta'
import Moonbeam from '../nodes/supported/Moonbeam'
import Moonriver from '../nodes/supported/Moonriver'
import Mythos from '../nodes/supported/Mythos'
import NeuroWeb from '../nodes/supported/NeuroWeb'
import NeuroWebPaseo from '../nodes/supported/NeuroWebPaseo'
import Nodle from '../nodes/supported/Nodle'
import NodlePaseo from '../nodes/supported/NodlePaseo'
import PAssetHub from '../nodes/supported/PAssetHub'
import Peaq from '../nodes/supported/Peaq'
import Pendulum from '../nodes/supported/Pendulum'
import Penpal from '../nodes/supported/Penpal'
import PeopleKusama from '../nodes/supported/PeopleKusama'
import PeoplePaseo from '../nodes/supported/PeoplePaseo'
import PeoplePolkadot from '../nodes/supported/PeoplePolkadot'
import PeopleWestend from '../nodes/supported/PeopleWestend'
import Phala from '../nodes/supported/Phala'
import Polimec from '../nodes/supported/Polimec'
import Quartz from '../nodes/supported/Quartz'
import RobonomicsKusama from '../nodes/supported/RobonomicsKusama'
import RobonomicsPolkadot from '../nodes/supported/RobonomicsPolkadot'
import Shiden from '../nodes/supported/Shiden'
import Subsocial from '../nodes/supported/Subsocial'
import Unique from '../nodes/supported/Unique'
import Zeitgeist from '../nodes/supported/Zeitgeist'
import ZeitgeistPaseo from '../nodes/supported/ZeitgeistPaseo'

export const nodes = <TApi, TRes>() => ({
  AssetHubPolkadot: new AssetHubPolkadot<TApi, TRes>(),
  Acala: new Acala<TApi, TRes>(),
  Ajuna: new Ajuna<TApi, TRes>(),
  Astar: new Astar<TApi, TRes>(),
  Unique: new Unique<TApi, TRes>(),
  Crust: new Crust<TApi, TRes>(),
  BifrostPolkadot: new BifrostPolkadot<TApi, TRes>(),
  BridgeHubPolkadot: new BridgeHubPolkadot<TApi, TRes>(),
  BridgeHubKusama: new BridgeHubKusama<TApi, TRes>(),
  Centrifuge: new Centrifuge<TApi, TRes>(),
  ComposableFinance: new ComposableFinance<TApi, TRes>(),
  Darwinia: new Darwinia<TApi, TRes>(),
  Hydration: new Hydration<TApi, TRes>(),
  Interlay: new Interlay<TApi, TRes>(),
  Heima: new Heima<TApi, TRes>(),
  Jamton: new Jamton<TApi, TRes>(),
  Moonbeam: new Moonbeam<TApi, TRes>(),
  AssetHubKusama: new AssetHubKusama<TApi, TRes>(),
  CoretimeKusama: new CoretimeKusama<TApi, TRes>(),
  CoretimePolkadot: new CoretimePolkadot<TApi, TRes>(),
  Encointer: new Encointer<TApi, TRes>(),
  Altair: new Altair<TApi, TRes>(),
  Amplitude: new Amplitude<TApi, TRes>(),
  Basilisk: new Basilisk<TApi, TRes>(),
  BifrostKusama: new BifrostKusama<TApi, TRes>(),
  CrustShadow: new CrustShadow<TApi, TRes>(),
  Crab: new Crab<TApi, TRes>(),
  Karura: new Karura<TApi, TRes>(),
  Kintsugi: new Kintsugi<TApi, TRes>(),
  Moonriver: new Moonriver<TApi, TRes>(),
  Laos: new Laos<TApi, TRes>(),
  Quartz: new Quartz<TApi, TRes>(),
  RobonomicsKusama: new RobonomicsKusama<TApi, TRes>(),
  RobonomicsPolkadot: new RobonomicsPolkadot<TApi, TRes>(),
  PeoplePolkadot: new PeoplePolkadot<TApi, TRes>(),
  PeopleKusama: new PeopleKusama<TApi, TRes>(),
  Shiden: new Shiden<TApi, TRes>(),
  Manta: new Manta<TApi, TRes>(),
  Nodle: new Nodle<TApi, TRes>(),
  NeuroWeb: new NeuroWeb<TApi, TRes>(),
  Pendulum: new Pendulum<TApi, TRes>(),
  Zeitgeist: new Zeitgeist<TApi, TRes>(),
  Collectives: new Collectives<TApi, TRes>(),
  Phala: new Phala<TApi, TRes>(),
  Subsocial: new Subsocial<TApi, TRes>(),
  KiltSpiritnet: new KiltSpiritnet<TApi, TRes>(),
  Curio: new Curio<TApi, TRes>(),
  Mythos: new Mythos<TApi, TRes>(),
  Peaq: new Peaq<TApi, TRes>(),
  Polimec: new Polimec<TApi, TRes>(),
  // Westend chains
  AssetHubWestend: new AssetHubWestend<TApi, TRes>(),
  BridgeHubWestend: new BridgeHubWestend<TApi, TRes>(),
  CollectivesWestend: new CollectivesWestend<TApi, TRes>(),
  CoretimeWestend: new CoretimeWestend<TApi, TRes>(),
  PeopleWestend: new PeopleWestend<TApi, TRes>(),
  Penpal: new Penpal<TApi, TRes>(),
  // Paseo chains
  AssetHubPaseo: new AssetHubPaseo<TApi, TRes>(),
  BridgeHubPaseo: new BridgeHubPaseo<TApi, TRes>(),
  CoretimePaseo: new CoretimePaseo<TApi, TRes>(),
  PAssetHub: new PAssetHub<TApi, TRes>(),
  PeoplePaseo: new PeoplePaseo<TApi, TRes>(),
  AjunaPaseo: new AjunaPaseo<TApi, TRes>(),
  BifrostPaseo: new BifrostPaseo<TApi, TRes>(),
  HeimaPaseo: new HeimaPaseo<TApi, TRes>(),
  HydrationPaseo: new HydrationPaseo<TApi, TRes>(),
  KiltPaseo: new KiltPaseo<TApi, TRes>(),
  LaosPaseo: new LaosPaseo<TApi, TRes>(),
  NeuroWebPaseo: new NeuroWebPaseo<TApi, TRes>(),
  NodlePaseo: new NodlePaseo<TApi, TRes>(),
  ZeitgeistPaseo: new ZeitgeistPaseo<TApi, TRes>()
})
