import Acala from '../nodes/supported/Acala'
import Altair from '../nodes/supported/Altair'
import Amplitude from '../nodes/supported/Amplitude'
import AssetHubKusama from '../nodes/supported/AssetHubKusama'
import AssetHubPolkadot from '../nodes/supported/AssetHubPolkadot'
import Astar from '../nodes/supported/Astar'
import Bajun from '../nodes/supported/Bajun'
import Basilisk from '../nodes/supported/Basilisk'
import BifrostKusama from '../nodes/supported/BifrostKusama'
import { BifrostPolkadot } from '../nodes/supported/BifrostPolkadot'
import Bitgreen from '../nodes/supported/Bitgreen'
import BridgeHubKusama from '../nodes/supported/BridgeHubKusama'
import BridgeHubPolkadot from '../nodes/supported/BridgeHubPolkadot'
import Calamari from '../nodes/supported/Calamari'
import { Centrifuge } from '../nodes/supported/Centrifuge'
import Collectives from '../nodes/supported/Collectives'
import ComposableFinance from '../nodes/supported/ComposableFinance'
import CoretimeKusama from '../nodes/supported/CoretimeKusama'
import CoretimePolkadot from '../nodes/supported/CoretimePolkadot'
import Crab from '../nodes/supported/Crab'
import Crust from '../nodes/supported/Crust'
import CrustShadow from '../nodes/supported/CrustShadow'
import Curio from '../nodes/supported/Curio'
import Darwinia from '../nodes/supported/Darwinia'
import Encointer from '../nodes/supported/Encointer'
import Heima from '../nodes/supported/Heima'
import Hydration from '../nodes/supported/Hydration'
import Imbue from '../nodes/supported/Imbue'
import Interlay from '../nodes/supported/Interlay'
import InvArchTinker from '../nodes/supported/InvArchTinker'
import Karura from '../nodes/supported/Karura'
import KiltSpiritnet from '../nodes/supported/KiltSpiritnet'
import Kintsugi from '../nodes/supported/Kintsugi'
import Manta from '../nodes/supported/Manta'
import Moonbeam from '../nodes/supported/Moonbeam'
import Moonriver from '../nodes/supported/Moonriver'
import Mythos from '../nodes/supported/Mythos'
import NeuroWeb from '../nodes/supported/NeuroWeb'
import Nodle from '../nodes/supported/Nodle'
import Parallel from '../nodes/supported/Parallel'
import ParallelHeiko from '../nodes/supported/ParallelHeiko'
import Peaq from '../nodes/supported/Peaq'
import Pendulum from '../nodes/supported/Pendulum'
import PeopleKusama from '../nodes/supported/PeopleKusama'
import PeoplePolkadot from '../nodes/supported/PeoplePolkadot'
import Phala from '../nodes/supported/Phala'
import Picasso from '../nodes/supported/Picasso'
import Polimec from '../nodes/supported/Polimec'
import Quartz from '../nodes/supported/Quartz'
import RobonomicsKusama from '../nodes/supported/RobonomicsKusama'
import RobonomicsPolkadot from '../nodes/supported/RobonomicsPolkadot'
import Shiden from '../nodes/supported/Shiden'
import Subsocial from '../nodes/supported/Subsocial'
import Turing from '../nodes/supported/Turing'
import Unique from '../nodes/supported/Unique'
import Zeitgeist from '../nodes/supported/Zeitgeist'

export const nodes = <TApi, TRes>() => ({
  AssetHubPolkadot: new AssetHubPolkadot<TApi, TRes>(),
  Acala: new Acala<TApi, TRes>(),
  Astar: new Astar<TApi, TRes>(),
  Unique: new Unique<TApi, TRes>(),
  Crust: new Crust<TApi, TRes>(),
  BifrostPolkadot: new BifrostPolkadot<TApi, TRes>(),
  BridgeHubPolkadot: new BridgeHubPolkadot<TApi, TRes>(),
  BridgeHubKusama: new BridgeHubKusama<TApi, TRes>(),
  Bitgreen: new Bitgreen<TApi, TRes>(),
  Centrifuge: new Centrifuge<TApi, TRes>(),
  ComposableFinance: new ComposableFinance<TApi, TRes>(),
  Darwinia: new Darwinia<TApi, TRes>(),
  Hydration: new Hydration<TApi, TRes>(),
  Interlay: new Interlay<TApi, TRes>(),
  Heima: new Heima<TApi, TRes>(),
  Moonbeam: new Moonbeam<TApi, TRes>(),
  Parallel: new Parallel<TApi, TRes>(),
  AssetHubKusama: new AssetHubKusama<TApi, TRes>(),
  CoretimeKusama: new CoretimeKusama<TApi, TRes>(),
  CoretimePolkadot: new CoretimePolkadot<TApi, TRes>(),
  Encointer: new Encointer<TApi, TRes>(),
  Altair: new Altair<TApi, TRes>(),
  Amplitude: new Amplitude<TApi, TRes>(),
  Bajun: new Bajun<TApi, TRes>(),
  Basilisk: new Basilisk<TApi, TRes>(),
  BifrostKusama: new BifrostKusama<TApi, TRes>(),
  Calamari: new Calamari<TApi, TRes>(),
  CrustShadow: new CrustShadow<TApi, TRes>(),
  Crab: new Crab<TApi, TRes>(),
  Imbue: new Imbue<TApi, TRes>(),
  InvArchTinker: new InvArchTinker<TApi, TRes>(),
  Karura: new Karura<TApi, TRes>(),
  Kintsugi: new Kintsugi<TApi, TRes>(),
  Moonriver: new Moonriver<TApi, TRes>(),
  ParallelHeiko: new ParallelHeiko<TApi, TRes>(),
  Picasso: new Picasso<TApi, TRes>(),
  Quartz: new Quartz<TApi, TRes>(),
  RobonomicsKusama: new RobonomicsKusama<TApi, TRes>(),
  RobonomicsPolkadot: new RobonomicsPolkadot<TApi, TRes>(),
  PeoplePolkadot: new PeoplePolkadot<TApi, TRes>(),
  PeopleKusama: new PeopleKusama<TApi, TRes>(),
  Shiden: new Shiden<TApi, TRes>(),
  Turing: new Turing<TApi, TRes>(),
  Manta: new Manta<TApi, TRes>(),
  Nodle: new Nodle<TApi, TRes>(),
  NeuroWeb: new NeuroWeb<TApi, TRes>(),
  Pendulum: new Pendulum<TApi, TRes>(),
  Zeitgeist: new Zeitgeist<TApi, TRes>(),
  Collectives: new Collectives<TApi, TRes>(),
  Phala: new Phala<TApi, TRes>(),
  Subsocial: new Subsocial<TApi, TRes>(),
  KiltSpiritnet: new KiltSpiritnet<TApi, TRes>(),
  Curio: new Curio<TApi, TRes>(),
  Mythos: new Mythos<TApi, TRes>(),
  Peaq: new Peaq<TApi, TRes>(),
  Polimec: new Polimec<TApi, TRes>()
})
