export enum EventName {
  GET_NODE_NAMES = 'Get Node Names',
  GET_ASSETS_OBJECT = 'Get Assets Object',
  GET_NODE_BY_PARA_ID = 'Get Node By Para Id',
  GET_ASSET_ID = 'Get Asset Id',
  GET_RELAYCHAIN_SYMBOL = 'Get Relaychain Symbol',
  GET_NATIVE_ASSETS = 'Get Native Assets',
  GET_OTHER_ASSETS = 'Get Other Assets',
  GET_ALL_ASSETS_SYMBOLS = 'Get All Assets Symbols',
  GET_DECIMALS = 'Get Decimals',
  HAS_SUPPORT_FOR_ASSET = 'Has Support For Asset',
  GET_PARA_ID = 'Get Para Id',
  GET_DEFAULT_PALLET = 'Get Default Pallet',
  GET_SUPPORTED_PALLETS = 'Get Supported Pallets',
  GENERATE_XCM_CALL = 'Generate XCM Call',
  GENERATE_XCM_CALL_HASH = 'Generate XCM Call Hash',
  GENERATE_ETH_CALL = 'Generate ETH Call',
  GENERATE_API_KEY = 'Generate API Key',
  GENERATE_ROUTER_EXTRINSICS = 'Generate router extrinsics',
  GENERATE_ROUTER_EXTRINSICS_HASH = 'Generate router extrinsics hash',
  CLAIM_ASSETS = 'Claim assets',
  CLAIM_ASSETS_HASH = 'Claim assets hash',
  GET_TRANSFER_INFO = 'Get Transfer Info',
  XCM_ANALYSER = 'XCM Analyser',
}
