export const API_URL = import.meta.env.VITE_API_URL as string;

export const ASSET_QUERIES = [
  'ASSETS_OBJECT',
  'ASSET_ID',
  'ASSET_MULTILOCATION',
  'RELAYCHAIN_SYMBOL',
  'NATIVE_ASSETS',
  'OTHER_ASSETS',
  'FEE_ASSETS',
  'ALL_SYMBOLS',
  'DECIMALS',
  'HAS_SUPPORT',
  'PARA_ID',
  'CONVERT_SS58',
  'ASSET_BALANCE',
  'EXISTENTIAL_DEPOSIT',
  'HAS_DRY_RUN_SUPPORT',
  'ETHEREUM_BRIDGE_STATUS',
  'PARA_ETH_FEES',
] as const;

export const PALLETS_QUERIES = [
  'ALL_PALLETS',
  'DEFAULT_PALLET',
  'PALLET_INDEX',
] as const;
