import { TNode, TNodeDetails } from '../types'

export const nodeNames = [
  'Statemint',
  'Acala',
  'Astar',
  'Bifrost-Polkadot',
  'Centrifuge',
  'Clover',
  'Composable-Finance',
  'Darwinia',
  'Efinity',
  'Equilibrium',
  'HydraDX',
  'Interlay',
  'Kapex',
  'Kilt',
  'Kylin',
  'Litentry',
  'Moonbeam',
  'OriginTrail',
  'Parallel',
  'Phala',
  'Unique',
  'Statemine',
  'Encointer',
  'Altair',
  'Amplitude',
  'Bajun',
  'Basilisk',
  'Bifrost-Kusama',
  'Pioneer',
  'Calamari',
  'Crust-Shadow',
  'Crab',
  'Dorafactory',
  'GM',
  'Imbue',
  'Integritee',
  'InvArch-Tinker',
  'Kabocha',
  'Karura',
  'Khala',
  'Kico',
  'Kintsugi',
  'Listen',
  'Litmus',
  'Mangata',
  'Moonriver',
  'Parallel-Heiko',
  'Picasso',
  'Pichiu',
  'Quartz',
  'Robonomics',
  'Shiden',
  'Snow',
  'Sora',
  'SubsocialX',
  'DataHighway',
  'Turing',
  'Zeitgeist'
] as const

// This maps our node names to names which polkadot libs are using
export const nodes: Record<TNode, TNodeDetails> = {
  Statemint: { name: 'statemint', type: 'polkadot' },
  Acala: { name: 'acala', type: 'polkadot' },
  Astar: { name: 'astar', type: 'polkadot' },
  'Bifrost-Polkadot': { name: 'bifrost', type: 'polkadot' },
  Centrifuge: { name: 'centrifuge', type: 'polkadot' },
  Clover: { name: 'clover', type: 'polkadot' },
  'Composable-Finance': { name: 'composableFinance', type: 'polkadot' },
  Darwinia: { name: 'darwinia', type: 'polkadot' },
  Efinity: { name: 'efinity', type: 'polkadot' },
  Equilibrium: { name: 'equilibrium', type: 'polkadot' },
  HydraDX: { name: 'hydra', type: 'polkadot' },
  Interlay: { name: 'interlay', type: 'polkadot' },
  Kapex: { name: 'kapex', type: 'polkadot' },
  Kilt: { name: 'kilt', type: 'polkadot' },
  Kylin: { name: 'kylin', type: 'polkadot' },
  Litentry: { name: 'litentry', type: 'polkadot' },
  Moonbeam: { name: 'moonbeam', type: 'polkadot' },
  OriginTrail: { name: 'origintrail-parachain', type: 'polkadot' },
  Parallel: { name: 'parallel', type: 'polkadot' },
  Phala: { name: 'phala', type: 'polkadot' },
  Unique: { name: 'unique', type: 'polkadot' },
  Statemine: { name: 'statemine', type: 'kusama' },
  Encointer: { name: 'encointer', type: 'kusama' },
  Altair: { name: 'altair', type: 'kusama' },
  Amplitude: { name: 'amplitude', type: 'kusama' },
  Bajun: { name: 'bajun', type: 'kusama' },
  Basilisk: { name: 'basilisk', type: 'kusama' },
  'Bifrost-Kusama': { name: 'bifrost', type: 'kusama' },
  Pioneer: { name: 'bitcountryPioneer', type: 'kusama' },
  Calamari: { name: 'calamari', type: 'kusama' },
  'Crust-Shadow': { name: 'shadow', type: 'kusama' },
  Crab: { name: 'crab', type: 'kusama' },
  Dorafactory: { name: 'dorafactory', type: 'kusama' },
  GM: { name: 'gm', type: 'kusama' },
  Imbue: { name: 'imbue', type: 'kusama' },
  Integritee: { name: 'integritee', type: 'kusama' },
  'InvArch-Tinker': { name: 'tinker', type: 'kusama' },
  Kabocha: { name: 'kabocha', type: 'kusama' },
  Karura: { name: 'karura', type: 'kusama' },
  Khala: { name: 'khala', type: 'kusama' },
  Kico: { name: 'kico', type: 'kusama' },
  Kintsugi: { name: 'kintsugi', type: 'kusama' },
  Listen: { name: 'listen', type: 'kusama' },
  Litmus: { name: 'litmus', type: 'kusama' },
  Mangata: { name: 'mangata', type: 'kusama' },
  Moonriver: { name: 'moonriver', type: 'kusama' },
  'Parallel-Heiko': { name: 'heiko', type: 'kusama' },
  Picasso: { name: 'picasso', type: 'kusama' },
  Pichiu: { name: 'pichiu', type: 'kusama' },
  Quartz: { name: 'quartz', type: 'kusama' },
  Robonomics: { name: 'robonomics', type: 'kusama' },
  Shiden: { name: 'shiden', type: 'kusama' },
  Snow: { name: 'snow', type: 'kusama' },
  Sora: { name: 'sora_ksm', type: 'kusama' },
  SubsocialX: { name: 'subsocialX', type: 'kusama' },
  DataHighway: { name: 'tanganika', type: 'kusama' },
  Turing: { name: 'turing', type: 'kusama' },
  Zeitgeist: { name: 'zeitgeist', type: 'kusama' }
}
