import { TNode, TPalletType } from '../types'

// Each node pallet map:

export const nodeToPallet: Record<TNode, TPalletType> = {
  Statemint: 'polkadotXCM',
  Acala: 'xTokens',
  Astar: 'polkadotXCM',
  BifrostPolkadot: 'xTokens',
  Bitgreen: 'polkadotXCM',
  Centrifuge: 'xTokens',
  Clover: 'xTokens',
  ComposableFinance: 'relayerXcm',
  Darwinia: 'polkadotXCM',
  Efinity: 'polkadotXCM',
  Equilibrium: 'polkadotXCM',
  HydraDX: 'xTokens',
  Interlay: 'xTokens',
  Kapex: 'polkadotXCM',
  Kilt: 'polkadotXCM',
  Kylin: 'ormlXTokens',
  Litentry: 'xTokens',
  Moonbeam: 'xTokens',
  OriginTrail: 'polkadotXCM',
  Parallel: 'xTokens',
  Phala: 'polkadotXCM',
  Unique: 'polkadotXCM',
  Statemine: 'polkadotXCM',
  Encointer: 'polkadotXCM',
  Altair: 'xTokens',
  Amplitude: 'xTokens',
  Bajun: 'polkadotXCM',
  Basilisk: 'xTokens',
  BifrostKusama: 'xTokens',
  Pioneer: 'xTokens',
  Calamari: 'xTokens',
  CrustShadow: 'xTokens',
  Crab: 'polkadotXCM',
  Dorafactory: 'xTokens',
  GM: 'polkadotXCM',
  Imbue: 'xTokens',
  Integritee: 'xTokens',
  InvArchTinker: 'xTokens',
  Kabocha: 'polkadotXCM',
  Karura: 'xTokens',
  Khala: 'polkadotXCM',
  Kico: 'xTokens',
  Kintsugi: 'xTokens',
  Listen: 'xTokens',
  Litmus: 'xTokens',
  Mangata: 'xTokens',
  Moonriver: 'xTokens',
  ParallelHeiko: 'xTokens',
  Picasso: 'xTokens',
  Pichiu: 'ormlXTokens',
  Quartz: 'polkadotXCM',
  Robonomics: 'polkadotXCM',
  Shiden: 'polkadotXCM',
  Snow: 'polkadotXCM',
  Sora: 'polkadotXCM',
  SubsocialX: 'polkadotXCM',
  DataHighway: 'polkadotXCM',
  Turing: 'xTokens',
  Zeitgeist: 'polkadotXCM'
}
