import { TNode, TPalletType } from '../types'

// Each node pallet map:

export const nodeToPallet: Record<TNode, TPalletType> = {
  Statemint: 'polkadotXCM',
  Acala: 'xTokens',
  Astar: 'polkadotXCM',
  BifrostPolkadot: 'xTokens',
  Bitgreen: 'polkadotXCM',
  Centrifuge: 'xTokens',
  Clover: 'xTokens',
  ComposableFinance: 'relayerXcm',
  Darwinia: 'polkadotXCM',
  HydraDX: 'xTokens',
  Interlay: 'xTokens',
  Kylin: 'ormlXTokens',
  Litentry: 'xTokens',
  Moonbeam: 'xTokens',
  Parallel: 'xTokens',
  Statemine: 'polkadotXCM',
  Encointer: 'polkadotXCM',
  Altair: 'xTokens',
  Amplitude: 'xTokens',
  Bajun: 'polkadotXCM',
  Basilisk: 'xTokens',
  BifrostKusama: 'xTokens',
  Pioneer: 'xTokens',
  Calamari: 'xTokens',
  CrustShadow: 'xTokens',
  Crab: 'polkadotXCM',
  Dorafactory: 'xTokens',
  Imbue: 'xTokens',
  Integritee: 'xTokens',
  InvArchTinker: 'xTokens',
  Karura: 'xTokens',
  Kico: 'xTokens',
  Kintsugi: 'xTokens',
  Listen: 'xTokens',
  Litmus: 'xTokens',
  Mangata: 'xTokens',
  Moonriver: 'xTokens',
  ParallelHeiko: 'xTokens',
  Picasso: 'xTokens',
  Pichiu: 'ormlXTokens',
  Quartz: 'polkadotXCM',
  Robonomics: 'polkadotXCM',
  Shiden: 'polkadotXCM',
  Turing: 'xTokens'
}
