import { TPalletType } from "../types";

//Each node pallet map:

export const Nodes: Record<string, TPalletType> = {
    'Statemint': 'polkadotXCM',
    'Acala': 'xTokens',
    'Astar': 'polkadotXCM',
    'Bifrost-Polkadot': 'xTokens',
    'Centrifuge': 'xTokens',
    'Clover': 'xTokens',
    'Darwinia': 'polkadotXCM',
    'Efinity': 'polkadotXCM',
    'Equilibrium': 'polkadotXCM',
    'HydraDX': 'xTokens',
    'Interlay': 'xTokens',
    'Kapex': 'polkadotXCM',
    'Kilt': 'polkadotXCM',
    'Kylin': 'ormlXTokens',
    'Litentry': 'xTokens',
    'Moonbeam': 'xTokens',
    'OriginTrail': 'polkadotXCM',
    'Parallel': 'xTokens',
    'Phala': 'polkadotXCM',
    'Unique': 'polkadotXCM',
    'Statemine': 'polkadotXCM',
    'Encointer': 'polkadotXCM',
    'Altair': 'xTokens',
    'Amplitude': 'xTokens',
    'Bajun': 'polkadotXCM',
    'Basilisk': 'xTokens',
    'Bifrost-Kusama': 'xTokens',
    'Pioneer': 'xTokens',
    'Calamari': 'xTokens',
    'Crust-Shadow': 'xTokens',
    'Crab': 'polkadotXCM',
    'Dorafactory': 'xTokens',
    'GM': 'polkadotXCM',
    'Imbue': 'xTokens',
    'Integritee': 'xTokens',
    'InvArch-Tinker': 'xTokens',
    'Kabocha': 'polkadotXCM',
    'Karura': 'xTokens',
    'Khala': 'polkadotXCM',
    'Kico': 'xTokens',
    'Kintsugi': 'xTokens',
    'Listen': 'xTokens',
    'Litmus': 'xTokens',
    'Mangata': 'xTokens',
    'Moonriver': 'xTokens',
    'Parallel-Heiko': 'xTokens',
    'Picasso': 'xTokens',
    'Pichiu': 'ormlXTokens',
    'Quartz': 'polkadotXCM',
    'Robonomics': 'polkadotXCM',
    'Shiden': 'polkadotXCM',
    'Snow': 'polkadotXCM',
    'Sora': 'polkadotXCM',
    'SubsocialX': 'polkadotXCM',
    'DataHighway': 'polkadotXCM',
    'Turing': 'xTokens',
    'Zeitgeist': 'polkadotXCM',
}